spring:
  profiles:
    active: dev
  mvc:
    locale: ko_KR
  messages:
    basename: classpath:messages/messages
    encoding: UTF-8
  session:
    maxInactiveInterval: 60
  jackson:
    property-naming-strategy: SNAKE_CASE
---
spring:
  application:
    name: Basic Server
    version: 1.0
  profiles:
    active: dev
  db1:
    datasource:
      hikari:
        maximum-pool-size: 10
        connection-test-query: SELECT 1
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 'hlhan'
        driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    maxInactiveInterval: 6000  # 세션  테스트용
  logging:
    config: classpath:logback-spring.xml
    # ERROR, WARN, INFO, DEBUG or TRACE
    level:
      com.hlhan.Basic: DEBUG

mybatis:
  type-aliases-package: com.hlhan.Basic
  config-location: classpath:mybatis/mybatis-config.xml
---
